---
- name: Stop running ansible-test processes
  ansible.builtin.command:
    argv:
      - pkill
      - -f
      - ansible-test
  register: ansibletest_process_cleanup
  changed_when: ansibletest_process_cleanup.rc == 0
  failed_when: ansibletest_process_cleanup.rc not in [0, 1]

- name: Remove test result directory
  ansible.builtin.file:
    path: /tmp/ansible-test-reports
    state: absent

- name: Remove test log directory
  ansible.builtin.file:
    path: /tmp/ansible-test-logs
    state: absent

- name: Display cleanup message
  ansible.builtin.debug:
    msg: "Test environment cleaned up successfully"
