---
namespace: vps
name: system
version: 1.1.0
readme: README.md
authors:
  - suai
description: "system roles collection"
license: [MIT]
repository: https://github.com/suainam/AuroraOps
tags:
  - ansible
  - infrastructure
  - linux
  - system
dependencies:
  community.general: ">=1.0.0"
