---
rclone_include_user_configs: true

# Rclone configuration file path
rclone_config_path: "/root/.config/rclone/rclone.conf"
rclone_config_dir: "{{ rclone_config_path | dirname }}"
rclone_user_config_dir: "{{ rclone_config_dir }}/rclone.conf.d"
rclone_darwin_config_path: "{{ (ansible_env.HOME | default('~')) }}/.config/rclone/rclone.conf"
rclone_darwin_config_dir: "{{ rclone_darwin_config_path | dirname }}"
rclone_darwin_user_config_dir: "{{ rclone_darwin_config_dir }}/rclone.conf.d"

# Cloud backup prefix
rclone_backup_path_prefix: ""

# Proxy configuration
rclone_use_proxy: "{{ proxy_enabled | default(false) }}"
rclone_http_proxy: "{{ proxy_http | default('') }}"
rclone_https_proxy: "{{ proxy_https | default('') }}"

# Secrets from Vault
rclone_onedrive_token: "{{ vault_rclone_onedrive_token }}"
rclone_onedrive_drive_id: "{{ vault_rclone_onedrive_drive_id }}"
rclone_gdrive_token: "{{ vault_rclone_gdrive_token }}"
