---
namespace: vps
name: services
version: 1.2.1
readme: README.md
authors:
  - suai
description: Service deployment and container roles collection
license:
  - MIT
repository: https://github.com/suainam/auroraops-services
tags:
  - ansible
  - infrastructure
  - linux
dependencies: {}
